server:
    error:
        include-message: always
        include-binding-errors: always

spring:
  datasource:
      password: 'password'
      url: jdbc:sqlserver://localhost:1433;database=galleryProject
      username: SA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000